### ISSUE TITLE
deadlock

### ISSUE THREAD

**Issue by fabiooshiro** [kelektiv/node-cron#381]
```js
console.log('fist')
new CronJob('0 0 9 4 * *', (function() {
  console.log('message');
}), null, true, 'America/Sao_Paulo');
console.log('second')
```
output
```first```

**Comment by ncb000gt** [comment]
Are you seeing this if you take out the DoM specificity? What about if you remove the timezone?

Have you been able to pinpoint anything inside the library as the culprit?

**Comment by ncb000gt** [comment]
I'm able to reproduce this. Thanks.

**Comment by ncb000gt** [comment]
@fabiooshiro we looked into this (mostly @jodevsa) and found some strange behavior when adding 1d and then setting the hours/minutes/seconds to 0. It appears as though only 23 hours are being added going into the 4th of the month.

I pushed a change that should help with the deadlock until we can figure out the larger resolving solution. Let me know if this works. @jodevsa is going to link to a ticket he's going to create over in the moment-tz project.

**Comment by ncb000gt** [comment]
The tests appear to be failing, but not individually. I'll look into these later when I get a moment.

**Comment by Roger13** [comment]
I'm still having this issue. Do we have a fix?

**Comment by ncb000gt** [comment]
@Roger13 did you pull the latest from npm? can you double check the cron `package.json` in your `node_modules` directory?

thanks!

**Comment by Roger13** [comment]
@ncb000gt Just ran a npm update, still having the issue, currently running `cron@1.4.1`

**Comment by ncb000gt** [comment]
@Roger13 sorry, I edited the comment above. Can you share any more? Thanks!

**Comment by ncb000gt** [comment]
@Roger13 hey, turns out we didn't publish the code to npm, sorry about this, slight miscomm. I've published 1.5.0 to npm. Pull that down and try it again. Let me know if you're still seeing this issue. Sorry about this and thanks!
